version: '3'

services:
  node:
    container_name: server
    image: node:14.3-slim
    ports:
      - "3333:3333"
    working_dir: "/home/node/app"
    volumes:
      - ./:/home/node/app
    command: "yarn dev"
    networks:
      - server

  postgres:
    image: postgres
    restart: always
    volumes:
      - pgsql:/var/lib/postgresql/data
    environment:
      POSTGRESQL_PASSWORD: server
      POSTGRESQL_USER: server
      POSTGRESQL_DB: serverdb
    ports:
      - 5434:5434

networks:
  server:
    driver: "bridge"

volumes:
  pgsql:
